services:
  db:
    build:
      context: requirements/mariadb
    container_name: mariadb
    volumes:
      - ../data/db:/var/lib/mysql
    restart: on-failure
    env_file: ".env"
    secrets:
      - mysql_root_password
      - mysql_user_password
    networks:
      - inception

  wordpress:
    build:
      context: requirements/wordpress
    container_name: wordpress
    volumes:
      - ../data/wordpress:/var/www/html
    restart: on-failure
    secrets:
      - mysql_user_password
      - wp_credentials
    env_file: ".env"
    depends_on:
      - db
    networks:
      - inception

  nginx:
    build:
      context: requirements/nginx
    container_name: nginx
    restart: on-failure
    ports:
      - "8443:443"
    volumes:
      - ../data/wordpress:/var/www/html
    env_file: ".env"
    depends_on:
      - wordpress
    networks:
      - inception

secrets:
  mysql_root_password:
    file: ../secrets/db_root_password.txt
  mysql_user_password:
    file: ../secrets/db_password.txt
  wp_credentials:
    file: ../secrets/credentials.txt

networks:
  inception:

