services:
  wordpress:
    build:
      context: requirements/wordpress
    container_name: wordpress
    volumes:
      - ../data/wordpress:/var/www/html
      - ./requirements/wordpress/conf:/tmp
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: t0t0r0_script_kiddy_42
      WORDPRESS_DB_NAME: wp_db
    depends_on:
      - db
    entrypoint: ["/bin/bash", "/tmp/wp-cli-setup.sh"]
      
  db:
    image: mariadb:10.5
    container_name: mariadb
    volumes:
      - ../data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
      MYSQL_ROOT_PASSWORD: t0t0r0_script_kiddy_42

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress