services:
  db:
    build:
      context: srcs/db
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure
    env_file: ".env"
    secrets:
      - mysql_root_password
      - mysql_user_password
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "/tmp/healthcheck.sh || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 10

  wordpress:
    build:
      context: srcs/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    restart: on-failure
    secrets:
      - mysql_user_password
      - wp_credentials
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - inception

  nginx:
    build:
      context: srcs/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: nginx
    restart: on-failure
    ports:
      - "${PORT_NO}:443"
    volumes:
      - wordpress:/var/www/html
    env_file: ".env"
    depends_on:
      - wordpress
    networks:
      - inception

secrets:
  mysql_root_password:
    file: secrets/db_root_password.txt
  mysql_user_password:
    file: secrets/db_password.txt
  wp_credentials:
    file: secrets/credentials.txt

networks:
  inception:

volumes:
  db_data:
  wordpress: